# Generated by Django 5.1 on 2024-10-16 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email_institucional', models.EmailField(max_length=254)),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=10)),
                ('matricula', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appweb.user'),
        ),
    ]
